// Generated by https://quicktype.io

export interface CastDetail {
    id:          number;
    name:        string;
    gender:      string;
    tmdbUrl:     string;
    profilePath: string;
    movieTitle:  MovieTitle[];
}

export interface MovieTitle {
    id:        number;
    title:     string;
    posterUrl: string;
}
