/*export interface MovieCard{
    id:number
    title: string;
    posterUrl: string;
    //releaseDate: Date;
}*/
//download the paste json as code extension
//create empty typesscript file
//copy the json data from swagger
//Ctrl + Shift + P => shortcut in VS Code for searching all the preferences// Generated by https://quicktype.io

// export interface MovieCard {
//     id: number;
//     title: string;
//     posterUrl: string;
// }
